{
    'name': 'Faculty Management',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'Manage faculty members in the history department',
    'description': 'Custom module for managing faculty members.',
    'author': 'Evan Ricketts',
    'depends': ['base'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/faculty_member_security.xml',
        'security/faculty_leave_security.xml',
        'views/faculty_member_views.xml',
        'views/faculty_leave_views.xml',
        'views/faculty_member_menus.xml',
    ],
    'installable': True,
    'application': True,
}
